import Link from 'next/link';
import { createClient } from '@/lib/supabase/server';
import { cities, getCity } from '@/lib/cities';
import { money } from '@/lib/missions';
import { actorDetails } from '@/lib/social';
export default async function Missions({searchParams}:{searchParams:Promise<{city?:string;community?:string;page?:string;q?:string}>}) {
 const {city,community,page,q:rawQuery}=await searchParams;const client=await createClient();const selectedCity=cities.find(c=>c.id===city);const queryText=(rawQuery??'').trim().slice(0,120);
 const {data:place}=selectedCity?await client.from('places').select('id').eq('source_key',selectedCity.id).maybeSingle():{data:null};
 const pageNumber=Math.max(0,Math.min(1000,Number.parseInt(page??'0',10)||0));
 let matchingPlaceIds:string[]=[];let matchingSdgMissionIds:string[]=[];
 if(queryText){const needle=queryText.toLocaleLowerCase('en');const matchingSourceKeys=cities.filter(c=>c.name.toLocaleLowerCase('en').includes(needle)||c.country.toLocaleLowerCase('en').includes(needle)||c.countryCode.toLocaleLowerCase('en').includes(needle)).map(c=>c.id);if(matchingSourceKeys.length){const {data:matchingPlaces}=await client.from('places').select('id').in('source_key',matchingSourceKeys.slice(0,500));matchingPlaceIds=(matchingPlaces??[]).map(item=>item.id);}const sdgMatch=needle.match(/^sdg\s*(\d{1,2})$/)||needle.match(/^(\d{1,2})$/);if(sdgMatch){const sdgNumber=Number(sdgMatch[1]);if(sdgNumber>=1&&sdgNumber<=17){const {data:sdgRows}=await client.from('mission_sdgs').select('mission_id').eq('sdg_number',sdgNumber).limit(500);matchingSdgMissionIds=(sdgRows??[]).map(row=>row.mission_id);}}}
 let query=client.from('missions').select('id,title,goal,location_text,funding_goal_amount,currency_code,city_id,manual_place,manual_country,community_id,created_by_actor_id,places(name,source_key)').is('removed_at',null).order('created_at',{ascending:false}).range(pageNumber*20,pageNumber*20+19);
 if(selectedCity){if(!place)return <p className="text-muted">This city is not available in the database yet.</p>;query=query.eq('city_id',place.id);}
 if(community&&/^[0-9a-f-]{36}$/i.test(community))query=query.eq('community_id',community);
 if(queryText){const safe=queryText.replace(/[%_,()]/g,' ').replace(/\s+/g,' ').trim();const filters=[safe?`title.ilike.%${safe}%`:null,safe?`manual_place.ilike.%${safe}%`:null,safe?`manual_country.ilike.%${safe}%`:null,matchingPlaceIds.length?`city_id.in.(${matchingPlaceIds.join(',')})`:null,matchingSdgMissionIds.length?`id.in.(${matchingSdgMissionIds.join(',')})`:null].filter(Boolean).join(',');if(filters)query=query.or(filters);else query=query.eq('id','00000000-0000-0000-0000-000000000000');}
 const {data:missions}=await query;
 const creatorDetails=await actorDetails((missions??[]).map(m=>m.created_by_actor_id));
 return <div className="space-y-6"><div className="flex flex-wrap justify-between gap-4"><div><p className="deck-label">PEOPLE · PLACES · PURPOSE</p><h1 className="mt-2 text-4xl">SDG Missions</h1><p className="mt-2 text-muted">Join real work in real places and contribute to the Sustainable Development Goals (SDGs) of the United Nations</p></div><Link href={selectedCity?`/missions/new?city=${selectedCity.id}`:'/missions/new'} className="h-fit rounded-xl bg-gold px-5 py-3 font-semibold text-navy">Create SDG Mission</Link></div>
 <form method="get" className="glass rounded-2xl p-4">{selectedCity&&<input type="hidden" name="city" value={selectedCity.id}/>} {community&&<input type="hidden" name="community" value={community}/>}<label className="block text-sm">Search SDG Missions<div className="mt-2 flex flex-col gap-2 sm:flex-row"><input name="q" defaultValue={queryText} placeholder="Search by SDG Mission, SDG number, place or country" className="w-full rounded-xl border border-line bg-panel-raised p-3"/><button className="rounded-xl bg-gold px-5 py-3 font-semibold text-navy">Search</button>{queryText&&<Link href={selectedCity?`/missions?city=${selectedCity.id}`:community?`/missions?community=${community}`:'/missions'} className="rounded-xl border border-line px-5 py-3 text-center text-gold">Clear</Link>}</div></label></form>
 {(selectedCity||community||queryText)&&<Link href="/missions" className="text-sm text-gold">Show all SDG Missions →</Link>}
 <div className="grid gap-4 md:grid-cols-2">{missions?.map(m=>{const place=m.places as unknown as {name:string;source_key:string}|null;const cityInfo=place?.source_key?getCity(place.source_key):null;const placeLabel=m.manual_place&&m.manual_country?`${m.manual_place}, ${m.manual_country}`:cityInfo?`${cityInfo.name}, ${cityInfo.country}`:place?.name??'City';return <Link key={m.id} href={`/missions/${m.id}`} className="glass rounded-2xl p-6 hover:border-gold"><p className="deck-label">{placeLabel}</p><h2 className="mt-3 text-xl">{m.title}</h2><p className="mt-2 text-sm text-muted">Created by {creatorDetails.get(m.created_by_actor_id)?.name||'Member'}</p><p className="mt-3 line-clamp-2 text-sm text-muted">{m.goal}</p><p className="mt-4 text-sm text-gold">Funding goal: {money(m.funding_goal_amount,m.currency_code)}</p></Link>})}</div>{!missions?.length&&<p className="glass rounded-2xl p-6 text-muted">{queryText?'No SDG Missions match your search.':'No SDG Missions have been added here yet.'}</p>}
 {missions?.length===20&&<Link href={`/missions?${selectedCity?`city=${selectedCity.id}&`:''}${community?`community=${community}&`:''}${queryText?`q=${encodeURIComponent(queryText)}&`:''}page=${pageNumber+1}`} className="text-gold">More SDG Missions →</Link>}
 </div>;
}
