import Link from 'next/link';
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { paymentAdmin, stripeServer } from '@/lib/payments';
import { money } from '@/lib/missions';
import { ReferralShare } from '@/components/referral-share';
export const metadata:Metadata={robots:{index:false,follow:false},referrer:'no-referrer'};
export default async function ThankYou({searchParams}:{searchParams:Promise<{session_id?:string}>}){const {session_id:id}=await searchParams;if(!id||!/^cs_(?:test_|live_)[a-zA-Z0-9]{10,}$/.test(id))notFound();const stripe=stripeServer();let session;try{session=await stripe.checkout.sessions.retrieve(id);}catch{notFound();}const checkoutId=session.metadata?.checkout_id;if(!checkoutId||session.client_reference_id!==checkoutId)notFound();const admin=paymentAdmin();const {data:checkout}=await admin.from('donation_checkouts').select('id,campaign_id,fundraiser_id,amount_minor,currency_code,frequency,stripe_session_id,donor_user_id').eq('id',checkoutId).maybeSingle();if(!checkout||checkout.stripe_session_id&&checkout.stripe_session_id!==id||session.amount_total!==checkout.amount_minor||session.currency?.toUpperCase()!==checkout.currency_code)notFound();const paid=session.payment_status==='paid';const {data:fundraiser}=checkout.fundraiser_id?await admin.from('fundraisers').select('slug,title').eq('id',checkout.fundraiser_id).single():{data:null};const {data:campaign}=await admin.from('fundraising_campaigns').select('title').eq('id',checkout.campaign_id).single();const {data:receipt}=paid?await admin.from('fundraiser_donations').select('receipt_url').eq('checkout_id',checkout.id).order('confirmed_at',{ascending:false}).limit(1).maybeSingle():{data:null};const {data:link}=fundraiser?await admin.from('fundraiser_referral_links').select('token').eq('fundraiser_id',checkout.fundraiser_id).single():{data:null};const shareTitle=fundraiser?.title||campaign?.title||'Support this Mission';const back=fundraiser?`/f/${fundraiser.slug}`:`/c/${checkout.campaign_id}`;
 return <main className="min-h-screen bg-navy px-5 py-12 text-ink"><div className="glass mx-auto max-w-2xl rounded-3xl p-8 sm:p-12"><Link href="/" className="text-lg font-black tracking-[.18em]">ALUNA<span className="text-gold">.</span></Link><p className="deck-label mt-12">{paid?'DONATION CONFIRMED':'PAYMENT PENDING'}</p><h1 className="mt-4 text-4xl">{paid?'Thank you for supporting this Mission.':'Your donation is being confirmed.'}</h1><p className="mt-5 text-muted">{paid?`${money(checkout.amount_minor/100,checkout.currency_code)}${checkout.frequency==='monthly'?' monthly':''} for ${shareTitle}.`:'Your payment is not yet confirmed. Please check back shortly or review your Stripe receipt.'}</p>{paid&&<section className="mt-8"><h2 className="mb-4 text-lg">Share Your Support</h2><ReferralShare {...(link?{token:link.token}:{path:`/c/${checkout.campaign_id}`})} title={shareTitle}/></section>}{paid&&receipt?.receipt_url&&/^https:\/\//.test(receipt.receipt_url)&&<a href={receipt.receipt_url} target="_blank" rel="noopener noreferrer" className="mt-6 inline-block text-sm text-gold">View Stripe receipt →</a>}<div className="mt-10 flex flex-wrap gap-4"><Link href={back} className="text-gold">Return to fundraising →</Link>{checkout.donor_user_id&&<Link href="/donations" className="text-gold">My donations →</Link>}</div></div></main>;
}
