import { NextRequest, NextResponse } from 'next/server';
import type Stripe from 'stripe';
import { paymentAdmin, stripeId, stripeServer, chargeReceipt, reportPaymentError } from '@/lib/payments';
export const runtime='nodejs';
function uuid(value:string|null|undefined){return !!value&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value);}
async function call(name:string,args:Record<string,unknown>){const admin=paymentAdmin();const {error}=await admin.rpc(name,args);if(error)throw new Error(`${name} failed: ${error.code}`);}
async function checkout(event:Stripe.Event){const id=(event.data.object as Stripe.Checkout.Session).id;const stripe=stripeServer();const session=await stripe.checkout.sessions.retrieve(id,{expand:['payment_intent.latest_charge']});const checkoutId=session.metadata?.checkout_id;if(!uuid(checkoutId)||session.client_reference_id!==checkoutId)throw new Error('Checkout metadata mismatch');const admin=paymentAdmin();const {data:row,error}=await admin.from('donation_checkouts').select('id,amount_minor,currency_code,frequency').eq('id',checkoutId).single();if(error||!row)throw new Error('Checkout missing');if(session.amount_total!==row.amount_minor||session.currency?.toUpperCase()!==row.currency_code||session.mode!==(row.frequency==='monthly'?'subscription':'payment'))throw new Error('Checkout amount or mode mismatch');
 const common={p_event:event.id,p_type:event.type,p_checkout:row.id,p_session:session.id,p_customer:stripeId(session.customer),p_email:session.customer_details?.email??null,p_name:session.customer_details?.name??null};
 if(session.mode==='payment'&&session.payment_status==='paid'){
  const paymentId=stripeId(session.payment_intent);if(!paymentId)throw new Error('PaymentIntent missing');const intent=typeof session.payment_intent==='string'?await stripe.paymentIntents.retrieve(paymentId,{expand:['latest_charge']}):session.payment_intent;if(!intent||intent.status!=='succeeded'||intent.amount_received!==row.amount_minor||intent.currency.toUpperCase()!==row.currency_code)throw new Error('PaymentIntent verification failed');const receipt=await chargeReceipt(stripe,intent);
  await call('record_confirmed_donation',{...common,p_payment:paymentId,p_invoice:null,p_charge:receipt.chargeId,p_amount:intent.amount_received,p_currency:intent.currency,p_receipt:receipt.receiptUrl,p_confirmed:new Date(intent.created*1000).toISOString()});return;
 }
 let state='checkout';if(event.type==='checkout.session.expired')state='expired';else if(event.type==='checkout.session.async_payment_failed')state='failed';
 await call('record_checkout_payment_event',{...common,p_subscription:stripeId(session.subscription),p_state:state});
}
async function subscriptionId(invoice:Stripe.Invoice){return stripeId(invoice.parent?.subscription_details?.subscription);}
async function subscriptionCheckout(id:string){const subscription=await stripeServer().subscriptions.retrieve(id);const checkoutId=subscription.metadata.checkout_id;if(!uuid(checkoutId))return null;return checkoutId;}
async function invoiceEvent(event:Stripe.Event){const stripe=stripeServer();const invoice=await stripe.invoices.retrieve((event.data.object as Stripe.Invoice).id);const subId=await subscriptionId(invoice);if(!subId)return;const checkoutId=invoice.parent?.subscription_details?.metadata?.checkout_id||await subscriptionCheckout(subId);if(!uuid(checkoutId))return;
 const admin=paymentAdmin();const {data:row,error}=await admin.from('donation_checkouts').select('id,amount_minor,currency_code,frequency,stripe_subscription_id').eq('id',checkoutId).single();if(error||!row||row.frequency!=='monthly'||row.stripe_subscription_id&&row.stripe_subscription_id!==subId)throw new Error('Invoice subscription mismatch');
 if(event.type==='invoice.payment_failed'){const current=await stripe.subscriptions.retrieve(subId);await call('record_subscription_event',{p_event:event.id,p_type:event.type,p_checkout:row.id,p_subscription:subId,p_state:current.status==='active'?'active':current.status==='canceled'?'canceled':'past_due'});return;}
 if(invoice.status!=='paid'||invoice.amount_paid<=0)return;
 if(invoice.amount_paid>row.amount_minor||invoice.currency.toUpperCase()!==row.currency_code)throw new Error('Invoice amount mismatch');
 const invoicePayments=await stripe.invoicePayments.list({invoice:invoice.id,limit:10});const paid=invoicePayments.data.find(payment=>payment.status==='paid'&&payment.payment.payment_intent);const paymentId=stripeId(paid?.payment.payment_intent);if(!paymentId)throw new Error('Paid invoice has no PaymentIntent');const intent=await stripe.paymentIntents.retrieve(paymentId,{expand:['latest_charge']});if(intent.status!=='succeeded'||intent.currency.toUpperCase()!==row.currency_code||intent.amount_received<invoice.amount_paid)throw new Error('Invoice payment verification failed');const receipt=await chargeReceipt(stripe,intent);
 await call('record_confirmed_donation',{p_event:event.id,p_type:event.type,p_checkout:row.id,p_session:null,p_payment:paymentId,p_invoice:invoice.id,p_charge:receipt.chargeId,p_amount:invoice.amount_paid,p_currency:invoice.currency,p_customer:stripeId(invoice.customer),p_email:invoice.customer_email,p_name:invoice.customer_name,p_receipt:invoice.hosted_invoice_url??receipt.receiptUrl,p_confirmed:new Date((invoice.status_transitions.paid_at??invoice.created)*1000).toISOString()});
}
async function subscriptionEvent(event:Stripe.Event){const subscription=event.type==='customer.subscription.deleted'?event.data.object as Stripe.Subscription:await stripeServer().subscriptions.retrieve((event.data.object as Stripe.Subscription).id);const checkoutId=subscription.metadata.checkout_id;if(!uuid(checkoutId))return;const state=subscription.status==='canceled'?'canceled':subscription.status==='active'?'active':'past_due';await call('record_subscription_event',{p_event:event.id,p_type:event.type,p_checkout:checkoutId,p_subscription:subscription.id,p_state:state});}
async function refundEvent(event:Stripe.Event){const refund=await stripeServer().refunds.retrieve((event.data.object as Stripe.Refund).id);const status=['pending','succeeded','failed','canceled'].includes(refund.status??'')?refund.status:'pending';if(!status)throw new Error('Refund status missing');await call('record_donation_refund',{p_event:event.id,p_type:event.type,p_payment:stripeId(refund.payment_intent),p_charge:stripeId(refund.charge),p_refund:refund.id,p_amount:refund.amount,p_status:status});}
export async function POST(request:NextRequest){const signature=request.headers.get('stripe-signature'),secret=process.env.STRIPE_WEBHOOK_SECRET;if(!signature||!secret)return new NextResponse('Webhook unavailable',{status:400});if(Number(request.headers.get('content-length')??0)>1_000_000)return new NextResponse('Payload too large',{status:413});let event:Stripe.Event;try{event=stripeServer().webhooks.constructEvent(await request.text(),signature,secret);}catch{return new NextResponse('Invalid signature',{status:400});}
 try{if(['checkout.session.completed','checkout.session.async_payment_succeeded','checkout.session.async_payment_failed','checkout.session.expired'].includes(event.type))await checkout(event);else if(['invoice.paid','invoice.payment_failed'].includes(event.type))await invoiceEvent(event);else if(['customer.subscription.created','customer.subscription.updated','customer.subscription.deleted'].includes(event.type))await subscriptionEvent(event);else if(['refund.created','refund.updated','refund.failed'].includes(event.type))await refundEvent(event);return NextResponse.json({received:true});}catch(error){reportPaymentError(error);return new NextResponse('Retry later',{status:500});}
}
