import { createClient } from '@/lib/supabase/server';
export async function First340Activity({profileId}:{profileId:string}){
 const c=await createClient();const [{data,error},{data:breakdown,error:breakdownError}]=await Promise.all([c.rpc('first340_candidate_activity',{p_profile:profileId}),c.rpc('first340_candidate_breakdown',{p_profile:profileId})]);
 if(error||breakdownError)return <p className="mt-3 text-sm text-amber-300">Candidate activity unavailable.</p>;
 const a=(data??[])[0] as {amount_raised:number;donors_recruited:number;referral_clicks:number;conversions:number;contributions:number;skills_contributed:number;time_contributed:number;work_contributed:number}|undefined;
 const b=(breakdown??[])[0] as {campaigns:number;attributed_donations:number;contribution_types:Record<string,number>}|undefined;
 const clicks=Number(a?.referral_clicks??0),attributed=Number(b?.attributed_donations??0);
 const metrics=[['Amount raised (EUR)',`€${Number(a?.amount_raised??0).toLocaleString('en-US',{maximumFractionDigits:2})}`],['Donors',String(a?.donors_recruited??0)],['Campaigns',String(b?.campaigns??0)],['Referral clicks',String(clicks)],['Attributed donations',String(attributed)],['Referral conversion','Not measurable'],['Referred fundraisers',String(a?.conversions??0)],['Contributions',String(a?.contributions??0)],['Skills',String(a?.skills_contributed??0)],['Time',`${Number(a?.time_contributed??0)} hours`],['Work',String(a?.work_contributed??0)]];
 return <div className="mt-3"><dl className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label,value])=><div key={label} className="rounded-lg border border-line bg-panel-raised p-3"><dt className="text-xs text-muted">{label}</dt><dd className={`mt-1 text-sm text-ink ${value==='Not measurable'?'':'metric-number'}`}>{value}</dd></div>)}</dl><p className="mt-3 text-xs">Other contributions: {Object.entries(b?.contribution_types??{}).filter(([kind])=>!['skills','time','work'].includes(kind)).map(([kind,count])=>`${kind}: ${count}`).join(' · ')||'None recorded'}. EUR amount raised and donor metrics follow confirmed payment records. Unique-click conversion is unavailable; no automatic selection score is calculated.</p></div>;
}
