import { createPost } from '@/app/(app)/feed/actions';
import type { Actor } from '@/lib/social';

export function PostComposer({actors,returnTo='/feed',repostOf,communityId,missionId}:{actors:Actor[];returnTo?:string;repostOf?:string;communityId?:string;missionId?:string}) {
 if(!actors.length)return null;
 return <form action={createPost} encType="multipart/form-data" className="glass space-y-4 rounded-2xl p-5"><h2 className="text-lg">{repostOf?'Share this post':'Create a post'}</h2><input type="hidden" name="return_to" value={returnTo}/>{repostOf&&<input type="hidden" name="repost_of_id" value={repostOf}/>} {communityId&&<input type="hidden" name="community_id" value={communityId}/>} {missionId&&<input type="hidden" name="mission_id" value={missionId}/>}
 <textarea name="body" required maxLength={5000} rows={repostOf?2:4} placeholder="Share an update with the Aluna network…" className="w-full rounded-xl border border-line bg-panel-raised p-3 text-ink"/>
 {!repostOf&&<label className="block text-sm text-muted">Photo or video<input name="media" type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,video/quicktime" className="mt-2 block w-full rounded-xl border border-line bg-panel-raised p-3 text-sm file:mr-4 file:rounded-lg file:border-0 file:bg-gold file:px-4 file:py-2 file:font-semibold file:text-navy"/></label>}
 <div className="flex flex-wrap items-center gap-3"><label className="text-sm text-muted">Post as <select name="actor_id" className="ml-2 rounded-lg border border-line bg-panel-raised p-2 text-ink">{actors.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>{!communityId&&!missionId&&<label className="text-sm text-muted">Audience <select name="visibility" className="ml-2 rounded-lg border border-line bg-panel-raised p-2 text-ink"><option value="public">Everyone</option><option value="followers">Followers</option></select></label>}<button className="ml-auto rounded-lg bg-gold px-5 py-2 font-semibold text-navy hover:bg-gold-soft">Post</button></div></form>;
}
