import Link from 'next/link';
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { createClient } from '@/lib/supabase/server';
import { Progress, type Total } from '@/lib/fundraising';
import { ReferralShare } from '@/components/referral-share';
import { DonationForm } from '@/components/donation-form';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const client=await createClient();const {data}=await client.from('fundraisers').select('title,story').eq('slug',slug).maybeSingle();return {title:data?`${data.title} | Aluna Fundraising`:'Aluna Fundraising',description:data?.story.slice(0,160)||'Support Aluna missions',robots:{index:true,follow:true}};}
export default async function PublicFundraiser({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{donation_error?:string;donation?:string}>}){const {slug}=await params;const {donation_error,donation}=await searchParams;const client=await createClient();const {data:fundraiser}=await client.from('fundraisers').select('id,campaign_id,kind,title,story,goal_amount').eq('slug',slug).maybeSingle();if(!fundraiser)notFound();const [{data:campaign},{data:link},{data:totals},{data:updates},{data:comments}]=await Promise.all([client.from('fundraising_campaigns').select('title,currency_code').eq('id',fundraiser.campaign_id).single(),client.from('fundraiser_referral_links').select('token').eq('fundraiser_id',fundraiser.id).single(),client.rpc('fundraising_totals',{p_campaign:fundraiser.campaign_id}),client.from('fundraiser_updates').select('id,body,created_at').eq('fundraiser_id',fundraiser.id).order('created_at',{ascending:false}).limit(10),client.from('fundraiser_comments').select('id,body,created_at').eq('fundraiser_id',fundraiser.id).order('created_at',{ascending:false}).limit(10)]);if(!campaign||!link)notFound();const total=((totals??[]) as Total[]).find(t=>t.fundraiser_id===fundraiser.id);const date=(value:string)=>new Intl.DateTimeFormat('en',{dateStyle:'medium'}).format(new Date(value));
 return <main className="min-h-screen bg-navy px-5 py-7 text-ink sm:px-8"><div className="mx-auto max-w-4xl space-y-6"><header className="flex items-center justify-between gap-4"><Link href="/" className="text-xl font-black tracking-[.18em]">ALUNA<span className="text-gold">.</span></Link><Link href="/login" className="text-sm text-gold">Sign in</Link></header><section className="glass rounded-3xl p-7 sm:p-10"><p className="deck-label">{fundraiser.kind==='team'?'TEAM':'PERSONAL'} FUNDRAISER · {campaign.title}</p><h1 className="mt-4 text-4xl sm:text-5xl">{fundraiser.title}</h1><div className="mt-8 max-w-xl"><Progress amount={Number(total?.amount_raised??0)} count={Number(total?.donor_count??0)} goal={Number(fundraiser.goal_amount)} currency={campaign.currency_code}/></div><div className="mt-6"><ReferralShare token={link.token} title={fundraiser.title}/></div></section>{(donation_error||donation)&&<p role="alert" className="rounded-xl border border-line p-3 text-sm">{donation_error?'Could not start checkout. Please check the amount and details or try again.':'Checkout was canceled. No donation was charged.'}</p>}<div id="donate"><DonationForm campaignId={fundraiser.campaign_id} fundraiserId={fundraiser.id} currency={campaign.currency_code}/></div><section className="glass rounded-3xl p-7 sm:p-8"><h2 className="text-xl">The story</h2><p className="mt-4 whitespace-pre-wrap text-muted">{fundraiser.story}</p></section><section className="grid gap-5 md:grid-cols-2"><div className="glass rounded-3xl p-6"><h2 className="text-lg">Updates</h2><div className="mt-4 space-y-4">{updates?.map(u=><article key={u.id} className="border-t border-line pt-3"><p className="text-xs text-gold">{date(u.created_at)}</p><p className="mt-2 whitespace-pre-wrap text-muted">{u.body}</p></article>)}{!updates?.length&&<p className="text-muted">No updates yet.</p>}</div></div><div className="glass rounded-3xl p-6"><h2 className="text-lg">Comments</h2><div className="mt-4 space-y-4">{comments?.map(c=><article key={c.id} className="border-t border-line pt-3"><p className="text-xs text-gold">{date(c.created_at)}</p><p className="mt-2 whitespace-pre-wrap text-muted">{c.body}</p></article>)}{!comments?.length&&<p className="text-muted">No comments yet.</p>}</div><Link href={`/fundraising/${slug}`} className="mt-5 inline-block text-sm text-gold">Sign in to comment →</Link></div></section></div></main>;
}
