import Link from 'next/link';
import { notFound } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { ownedActors, actorDetails, relativeDate } from '@/lib/social';
import { getCity } from '@/lib/cities';
import { evidenceTypes, verificationLevels, type Proof } from '@/lib/proofs';
import { Card } from '@/components/ui';
import { verifyProof } from '../actions';
export default async function ProofPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string;status?:string}>}){
 const {id}=await params;const {error,status}=await searchParams;const client=await createClient();
 const {data}=await client.from('proofs').select('*').eq('id',id).maybeSingle();if(!data)notFound();const proof=data as Proof;
 const [{data:events},{data:mission},{data:place},{data:contribution},actors,{data:reviewLevel}]=await Promise.all([
  client.from('proof_verification_events').select('id,previous_level,new_level,verifier_actor_id,method,reason,recorded_at').eq('proof_id',id).order('recorded_at',{ascending:true}).order('id',{ascending:true}),
  proof.mission_id?client.from('missions').select('title').eq('id',proof.mission_id).maybeSingle():Promise.resolve({data:null}),
  proof.city_id?client.from('places').select('source_key,name').eq('id',proof.city_id).maybeSingle():Promise.resolve({data:null}),
  proof.contribution_id?client.from('contributions').select('title').eq('id',proof.contribution_id).maybeSingle():Promise.resolve({data:null}),
  ownedActors(),client.rpc('my_proof_verifier_level'),
 ]);
 const details=await actorDetails([proof.actor_id,...(events??[]).map(e=>e.verifier_actor_id)]);
 const reviewerActors=actors.filter(a=>a.id!==proof.actor_id);const city=place?.source_key?getCity(place.source_key):null;const maxLevel=Number(reviewLevel??0);
 return <div className="space-y-6"><Link href="/proofs" className="text-sm text-gold">← Proofs</Link>{error&&<p role="alert" className="rounded-xl border border-red-700 p-3 text-red-300">Review was not saved. Check your authorization, reason and the current level.</p>}{status&&<p role="status" className="text-gold">Review recorded.</p>}
 <header className="rounded-3xl border border-line bg-panel p-7 sm:p-10"><p className="deck-label">{verificationLevels[proof.verification_level]}</p><h1 className="mt-4 text-4xl">Proof of impact</h1><p className="mt-3 text-sm text-muted">{proof.occurred_on} · {evidenceTypes.find(e=>e.value===proof.evidence_type)?.label}</p></header>
 <Card title="Result & evidence"><p className="whitespace-pre-wrap text-ink">{proof.result_text}</p><h3 className="mt-6 font-semibold text-ink">Supporting evidence</h3><p className="mt-2 whitespace-pre-wrap">{proof.evidence_description}</p>{proof.evidence_url&&<a href={proof.evidence_url} target="_blank" rel="noopener noreferrer" className="mt-3 inline-block break-all text-gold">Open submitted evidence ↗</a>}{proof.latitude!==null&&proof.longitude!==null&&<p className="mt-3 text-sm">Submitted coordinates: {proof.latitude}, {proof.longitude}</p>}<p className="mt-4 text-xs">External links, coordinates and sensor references are submitted evidence; Aluna has not automatically authenticated them.</p></Card>
 <Card title="Traceability"><div className="space-y-2 text-sm"><p>Contributor: <Link href={details.get(proof.actor_id)?.href??'/proofs'} className="text-gold">{details.get(proof.actor_id)?.name??'Member'}</Link></p>{proof.contribution_id&&<p>Contribution: <Link href={`/contributions/${proof.contribution_id}`} className="text-gold">{contribution?.title??'View contribution'}</Link></p>}{proof.post_id&&<p>Post: <Link href={`/posts/${proof.post_id}`} className="text-gold">View original post</Link></p>}{proof.post_snapshot&&<p className="whitespace-pre-wrap">Post at submission: {proof.post_snapshot}</p>}{proof.mission_id&&<p>Mission: <Link href={`/missions/${proof.mission_id}`} className="text-gold">{mission?.title??'View mission'}</Link></p>}{city&&<p>City: <Link href={`/cities/${city.id}`} className="text-gold">{city.name}</Link></p>}</div></Card>
 <Card title="Verification history"><div className="space-y-4">{events?.map(event=><div key={event.id} className="rounded-xl border border-line p-4"><p className="font-semibold text-ink">{verificationLevels[event.new_level]} · {relativeDate(event.recorded_at)}</p><p className="mt-1 text-xs">{event.previous_level?`${verificationLevels[event.previous_level]} → `:''}{event.method.replaceAll('_',' ')} · <Link className="text-gold" href={details.get(event.verifier_actor_id)?.href??'/proofs'}>{details.get(event.verifier_actor_id)?.name??'Reviewer'}</Link></p><p className="mt-2 whitespace-pre-wrap text-sm">{event.reason}</p></div>)}</div></Card>
 {reviewerActors.length>0&&(proof.verification_level===1||maxLevel>=3)&&<Card title="Record a review"><p className="mb-4 text-sm">Your decision and explanation will appear in the public audit history. You cannot verify a proof you control.</p><form action={verifyProof} className="max-w-xl space-y-4"><input type="hidden" name="proof_id" value={id}/><input type="hidden" name="expected_level" value={proof.verification_level}/><label className="block text-sm">Review as<select name="actor_id" className="mt-2 w-full rounded-xl border border-line bg-panel-raised p-3">{reviewerActors.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="block text-sm">New level<select name="new_level" className="mt-2 w-full rounded-xl border border-line bg-panel-raised p-3">{proof.verification_level===1&&<option value="2">L2 Peer-Attested</option>}{maxLevel>=3&&[1,2,3,4].filter(level=>level!==proof.verification_level&&(level!==4||maxLevel>=4)).map(level=><option key={level} value={level}>{verificationLevels[level]}</option>)}</select></label><label className="block text-sm">Reason and what you checked<textarea name="reason" required minLength={10} maxLength={2000} rows={4} className="mt-2 w-full rounded-xl border border-line bg-panel-raised p-3"/></label><button className="rounded-xl bg-gold px-5 py-3 font-semibold text-navy">Record review</button></form></Card>}
 </div>;
}
