import Link from 'next/link';
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { createClient } from '@/lib/supabase/server';
import { Progress, campaignTotal, type Total } from '@/lib/fundraising';
import { ReferralShare } from '@/components/referral-share';
import { DonationForm } from '@/components/donation-form';
export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const {id}=await params;const client=await createClient();const {data}=await client.from('fundraising_campaigns').select('title,story').eq('id',id).is('removed_at',null).is('archived_at',null).maybeSingle();return {title:data?`${data.title} | Aluna Fundraising`:'Aluna Fundraising',description:data?.story.slice(0,160)||'Support Aluna missions'};}
export default async function PublicCampaign({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{donation_error?:string;donation?:string}>}){const {id}=await params;const {donation_error,donation}=await searchParams;const client=await createClient();const {data:campaign}=await client.from('fundraising_campaigns').select('id,title,story,goal_amount,currency_code').eq('id',id).maybeSingle();if(!campaign)notFound();const [{data:fundraisers},{data:totals}]=await Promise.all([client.from('fundraisers').select('id,slug,title,kind,goal_amount').eq('campaign_id',id).order('created_at',{ascending:false}).limit(50),client.rpc('fundraising_totals',{p_campaign:id})]);const summary=campaignTotal((totals??[]) as Total[]);const byFundraiser=new Map(((totals??[]) as Total[]).map(t=>[t.fundraiser_id,t]));return <main className="min-h-screen bg-navy px-5 py-7 text-ink sm:px-8"><div className="mx-auto max-w-4xl space-y-6"><header className="flex items-center justify-between"><Link href="/" className="text-xl font-black tracking-[.18em]">ALUNA<span className="text-gold">.</span></Link><Link href="/login" className="text-sm text-gold">Sign in</Link></header><section className="glass rounded-3xl p-7 sm:p-10"><p className="deck-label">MISSION CAMPAIGN</p><h1 className="mt-4 text-4xl">{campaign.title}</h1><div className="mt-8 max-w-xl"><Progress amount={summary.amount} count={summary.count} goal={Number(campaign.goal_amount)} currency={campaign.currency_code}/></div><div className="mt-6"><ReferralShare path={`/c/${id}`} title={campaign.title}/></div></section>{(donation_error||donation)&&<p role="alert" className="rounded-xl border border-line p-3 text-sm">{donation_error?'Could not start checkout. Please check the amount and details or try again.':'Checkout was canceled. No donation was charged.'}</p>}<div id="donate"><DonationForm campaignId={id} currency={campaign.currency_code}/></div><section className="glass rounded-3xl p-7 sm:p-8"><h2 className="text-xl">Campaign story</h2><p className="mt-4 whitespace-pre-wrap text-muted">{campaign.story}</p></section><section className="glass rounded-3xl p-7 sm:p-8"><h2 className="text-xl">Fundraisers</h2><div className="mt-5 space-y-3">{fundraisers?.map(f=>{const total=byFundraiser.get(f.id);return <Link key={f.id} href={`/f/${f.slug}`} className="block rounded-xl border border-line p-4 hover:border-gold"><p className="mb-3 text-gold">{f.title} · {f.kind==='team'?'Team':'Personal'} →</p><Progress amount={Number(total?.amount_raised??0)} count={Number(total?.donor_count??0)} goal={Number(f.goal_amount)} currency={campaign.currency_code}/></Link>})}{!fundraisers?.length&&<p className="text-muted">No fundraisers yet.</p>}</div><Link href={`/fundraising/new?campaign=${id}`} className="mt-5 inline-block text-sm text-gold">Sign in to start a fundraiser →</Link></section></div></main>}
