import Link from 'next/link';
import { createClient } from '@/lib/supabase/server';
import { actorDetails, ownedActors, relativeDate } from '@/lib/social';
import { markNotificationRead } from './actions';
export default async function Notifications() {
 const actors=await ownedActors();const client=await createClient();const {data:items}=actors.length?await client.from('notifications').select('id,recipient_actor_id,sender_actor_id,kind,target_id,is_read,created_at').in('recipient_actor_id',actors.map(a=>a.id)).order('created_at',{ascending:false}).limit(50):{data:[]};
 const senders=await actorDetails((items??[]).flatMap(n=>n.sender_actor_id?[n.sender_actor_id]:[]));
 return <div className="space-y-6"><div><p className="deck-label">YOUR NETWORK</p><h1 className="mt-2 text-4xl">Notifications</h1></div><div className="space-y-3">{items?.map(item=>{const sender=item.sender_actor_id?senders.get(item.sender_actor_id):null;const href=item.kind==='message'?`/messages?conversation=${item.target_id}`:item.kind==='comment'||item.kind==='reaction'?`/posts/${item.target_id}`:sender?.href||'/profile';return <div key={item.id} className={`glass flex flex-wrap items-center justify-between gap-3 rounded-xl p-4 ${item.is_read?'opacity-70':'border-gold/40'}`}><div><span className="text-sm text-muted">{relativeDate(item.created_at)} · {actors.find(a=>a.id===item.recipient_actor_id)?.name}</span><p className="mt-1"><Link href={sender?.href||'/profile'} className="text-gold">{sender?.name||'Someone'}</Link> {item.kind==='follow'?'followed you':item.kind==='connection'?'sent a connection request':item.kind==='comment'?'commented on a post':item.kind==='reaction'?'reacted to a post':'sent a message'}.</p><Link href={href} className="text-sm text-gold hover:underline">View →</Link></div>{!item.is_read&&<form action={markNotificationRead}><input type="hidden" name="id" value={item.id}/><button className="text-sm text-muted hover:text-ink">Mark read</button></form>}</div>})}{!items?.length&&<p className="glass rounded-xl p-6 text-muted">No notifications yet.</p>}</div></div>;
}
