import Link from 'next/link';
import { notFound } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { actorDetails, ownedActors, relativeDate } from '@/lib/social';
import { Progress, campaignTotal, type Total, type Campaign } from '@/lib/fundraising';
import { Card } from '@/components/ui';
import { ReferralShare } from '@/components/referral-share';
import { DonationForm } from '@/components/donation-form';
export default async function CampaignPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const client=await createClient();const {data}=await client.from('fundraising_campaigns').select('*,missions(title)').eq('id',id).maybeSingle();if(!data)notFound();const campaign=data as Campaign & {missions:{title:string}|null};const [{data:fundraisers},{data:totals}]=await Promise.all([client.from('fundraisers').select('id,slug,title,kind,actor_id,goal_amount').eq('campaign_id',id).order('created_at',{ascending:false}).limit(100),client.rpc('fundraising_totals',{p_campaign:id})]);const summary=campaignTotal((totals??[]) as Total[]);const byFundraiser=new Map(((totals??[]) as Total[]).map(t=>[t.fundraiser_id,t]));const actors=await actorDetails([campaign.actor_id,...(fundraisers??[]).map(f=>f.actor_id)]);const mine=await ownedActors();const canEdit=mine.some(a=>a.id===campaign.actor_id);
 return <div className="space-y-6"><Link href="/fundraising" className="text-sm text-gold">← Fundraising</Link><header className="rounded-3xl border border-line bg-panel p-7 sm:p-10"><p className="deck-label">MISSION CAMPAIGN</p><h1 className="mt-3 text-4xl">{campaign.title}</h1><p className="mt-3 text-muted"><Link href={`/missions/${campaign.mission_id}`} className="text-gold">{campaign.missions?.title} →</Link> · {actors.get(campaign.actor_id)?.name} · {relativeDate(campaign.created_at)}</p><div className="mt-7 max-w-xl"><Progress amount={summary.amount} count={summary.count} goal={Number(campaign.goal_amount)} currency={campaign.currency_code}/></div><div className="mt-6 flex flex-wrap items-center gap-4"><Link href={`/fundraising/new?campaign=${id}`} className="inline-block rounded-xl bg-gold px-5 py-3 font-semibold text-navy">Start a fundraiser</Link>{canEdit&&<Link href={`/fundraising/campaigns/${id}/edit`} className="text-sm text-gold">Edit campaign →</Link>}</div></header><ReferralShare path={`/c/${id}`} title={campaign.title}/><DonationForm campaignId={id} currency={campaign.currency_code}/><Card title="Campaign story"><p className="whitespace-pre-wrap">{campaign.story}</p></Card><Card title="Fundraisers"><div className="space-y-3">{fundraisers?.map(f=>{const total=byFundraiser.get(f.id);return <Link key={f.id} href={`/fundraising/${f.slug}`} className="block rounded-xl border border-line p-4 hover:border-gold"><p className="text-gold">{f.title} · {f.kind==='team'?'Team':'Personal'}</p><p className="my-2 text-xs">By {actors.get(f.actor_id)?.name}</p><Progress amount={Number(total?.amount_raised??0)} count={Number(total?.donor_count??0)} goal={Number(f.goal_amount)} currency={campaign.currency_code}/></Link>})}{!fundraisers?.length&&<p>No fundraisers yet.</p>}</div></Card></div>;
}
