import Link from 'next/link';
import { createClient } from '@/lib/supabase/server';
import { Progress, campaignTotal, type Total } from '@/lib/fundraising';
import { getCity } from '@/lib/cities';
import { actorDetails } from '@/lib/social';
import { sdgLabel } from '@/lib/sdgs';
export default async function Fundraising({searchParams}:{searchParams:Promise<{page?:string}>}){const {page}=await searchParams;const offset=Math.max(0,Math.min(1000,Number.parseInt(page??'0',10)||0));const client=await createClient();const {data:campaigns}=await client.from('fundraising_campaigns').select('id,title,story,goal_amount,currency_code,mission_id,actor_id,missions(title,manual_place,manual_country,places(name,source_key))').is('removed_at',null).is('archived_at',null).order('created_at',{ascending:false}).range(offset*20,offset*20+19);
 const missionIds=[...new Set((campaigns??[]).map(c=>c.mission_id))];
 const {data:sdgRows}=missionIds.length?await client.from('mission_sdgs').select('mission_id,sdg_number').in('mission_id',missionIds).order('sdg_number'):{data:[]};
 const sdgsByMission=new Map<string,number[]>();for(const row of sdgRows??[]){const values=sdgsByMission.get(row.mission_id)??[];values.push(row.sdg_number);sdgsByMission.set(row.mission_id,values);}
 const totals=await Promise.all((campaigns??[]).map(async c=>{const {data}=await client.rpc('fundraising_totals',{p_campaign:c.id});return [c.id,campaignTotal((data??[]) as Total[])] as const;}));const raised=new Map(totals);const creatorDetails=await actorDetails((campaigns??[]).map(c=>c.actor_id));
 return <div className="space-y-6"><div className="flex flex-wrap justify-between gap-4"><div><p className="deck-label">SDG MISSION FUNDRAISING</p><h1 className="mt-2 text-4xl">SDG Fundraising</h1><p className="mt-2 text-muted">Campaigns connected to SDG missions.</p></div><div className="flex flex-wrap gap-3"><Link href="/fundraising/performance" className="h-fit rounded-xl border border-line px-5 py-3 text-gold">SDG Fundraising performance</Link><Link href="/fundraising/campaigns/new" className="h-fit rounded-xl bg-gold px-5 py-3 font-semibold text-navy">Create campaign</Link></div></div><div className="grid gap-4 md:grid-cols-2">{campaigns?.map(c=>{const total=raised.get(c.id)??{amount:0,count:0};const mission=c.missions as unknown as {title:string;manual_place:string|null;manual_country:string|null;places:{name:string;source_key:string}|null}|null;const cityInfo=mission?.places?.source_key?getCity(mission.places.source_key):null;const placeLabel=mission?.manual_place&&mission.manual_country?`${mission.manual_place}, ${mission.manual_country}`:cityInfo?`${cityInfo.name}, ${cityInfo.country}`:mission?.places?.name??null;const sdgText=(sdgsByMission.get(c.mission_id)??[]).map(sdgLabel).join(' · ');return <Link key={c.id} href={`/fundraising/campaigns/${c.id}`} className="glass rounded-2xl p-6 hover:border-gold"><p className="text-sm font-semibold text-gold">{mission?.title||'SDG Mission'}</p>{placeLabel&&<p className="mt-2 text-sm text-ink">{placeLabel}</p>}{sdgText&&<p className="mt-2 text-sm text-gold">{sdgText}</p>}<h2 className="mt-3 text-xl text-ink">{c.title}</h2><p className="mt-2 text-sm text-gold">Created by {creatorDetails.get(c.actor_id)?.name||'Member'}</p><p className="my-4 line-clamp-2 text-sm text-ink">{c.story}</p><Progress amount={total.amount} count={total.count} goal={Number(c.goal_amount)} currency={c.currency_code}/></Link>})}</div>{!campaigns?.length&&<p className="glass rounded-2xl p-6 text-muted">No campaigns yet.</p>}{campaigns?.length===20&&<Link href={`/fundraising?page=${offset+1}`} className="text-gold">More campaigns →</Link>}</div>;
}
